name: Tests

on:
  push:
    branches:
    - main
    paths:
    - project/**
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: ./project/tests.sh
