name: Tests

on:
  push:
    branches:
    - main
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup environment
        run: pip install -r ./project/requirements.txt
      - name: Run tests
        run:  |
            chmod +x ./project/tests.sh
            ./project/tests.sh
