name: Tests

on:
  push:
    branches:
    - main
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup environment
        run: pip install -r ./project/requirements.txt
      - name: Run tests
        run:  |
            cd project
            chmod +x tests.sh
            bash tests.sh
